my_string = input()
my_string = len(my_string)
print(my_string)
my_string = input()
my_string = my_string.upper()
print(my_string)
my_string = input()
my_string = my_string.lower()
print(my_string)
my_string = input()
my_string = my_string.replace(' ','')
print(my_string)
my_string = input()
my_string = my_string[0]
print(my_string)
my_string = input()
my_string = my_string[-1]
print(my_string)
